version: '3.8'

services:
  meldeplattform-scraper:
    build: .
    image: meldeplattform-scraper:latest
    container_name: meldeplattform-scraper
    restart: unless-stopped
    
    # Environment variables
    environment:
      - TZ=Europe/Berlin
    
    # Volume for persistent cache
    volumes:
      - ./cache:/app/cache
      - ./output:/app/output
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD", "test", "-f", "/app/cache/*.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Run once and exit (for cron-like behavior)
    # Remove 'restart: unless-stopped' and uncomment below for one-shot execution
    # restart: "no"
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Run on schedule using cron-like container
  scheduler:
    image: alpine:3.19
    container_name: meldeplattform-scheduler
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./cache:/app/cache
      - ./output:/app/output
    command: >
      sh -c "
        apk add --no-cache docker-cli &&
        echo '0 */6 * * * docker run --rm -v ./cache:/app/cache -v ./output:/app/output meldeplattform-scraper:latest' | crontab - &&
        crond -f
      "
    profiles:
      - scheduler